[profile.default]

# compilation
optimizer = true
optimizer_runs = 200

# paths
src = 'src'
test = 'test'
script = 'script'

# contracts in libs are excluded from code coverage reports
libs = ['node_modules', 'lib']

[fuzz]
runs = 5000
max_test_rejects = 1000000

[invariant]
runs = 1000
depth = 100

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
